---
- name: Launch
  block:
  - name: Checkout repo
    git:
      repo: https://github.com/Validat0rs/thorchain-node-launcher
      dest: /usr/src/thorchain-node-launcher

  - name: Checkout master
    shell: git checkout master
    args:
      chdir: /usr/src/thorchain-node-launcher

  - name: Set git config
    shell: |
      git config pull.rebase true
      git config rebase.autoStash true
    args:
      chdir: /usr/src/thorchain-node-launcher

  - name: Install helm
    shell: make helm
    args:
      chdir: /usr/src/thorchain-node-launcher/node-launcher

  - name: Install helm-plugins
    shell: make helm-plugins
    args:
      chdir: /usr/src/thorchain-node-launcher/node-launcher

  - name: Install tools
    shell: make tools
    args:
      chdir: /usr/src/thorchain-node-launcher/node-launcher

  - name: Daemons
    block:
    - name: Checkout branch
      shell: git checkout feat/daemons
      args:
        chdir: /usr/src/thorchain-node-launcher/node-launcher

    - name: Install
      shell: yes | NAME=daemons TYPE=daemons NET=mainnet make install
      args:
        chdir: /usr/src/thorchain-node-launcher/node-launcher
    when: launch_daemons == "true"

  - name: THORNode
    block:
    - name: Checkout branch
      shell: git checkout feat/thornode
      args:
        chdir: /usr/src/thorchain-node-launcher/node-launcher

    - name: Install
      shell: |
        ./scripts/install-thornode.exp {{ thornode_namespace }} {{ thornode_password }}
      args:
        chdir: /usr/src/thorchain-node-launcher/node-launcher 
    when: launch_thornode == "true"
