---
- name: Setup
  block:
  - name: microk8s
    block:
    - name: Install
      community.general.snap:
        name: microk8s
        classic: true
        channel: 1.30/stable

    - name: Enable dns
      shell: microk8s enable dns

    - name: Enable hostpath-storage
      shell: microk8s enable hostpath-storage

    - name: Enable metrics-server
      shell: microk8s enable metrics-server

    - name: Enable metallb
      shell: "microk8s enable metallb:{{ ansible_host }}/32"

    - name: Create the microk8s config directory
      ansible.builtin.file:
        path: $HOME/.kube
        state: directory
        mode: "0755"

    - name: Generate microk8s config
      shell: microk8s config > $HOME/.kube/config

    - name: Update .bashrc
      lineinfile:
        path: $HOME/.bashrc
        line: | 
          export KUBECONFIG=$HOME/.kube/config
          export KUBE_EDITOR="vi"
          source <(kubectl completion bash)
        state: present

  - name: k9s
    block:
      - name: Install k9s
        community.general.snap:
          name: k9s

      - name: Fix k9s
        ansible.builtin.file:
          src: /snap/k9s/current/bin/k9s
          dest: /snap/bin/k9s
          state: link

  - name: Install kubectl
    community.general.snap:
      name: kubectl
      classic: true

  - name: coredns
    block:
      - name: Remove resolv.conf
        shell: rm /etc/resolv.conf

      - name: Link resolv.conf
        ansible.builtin.file:
          src: /run/systemd/resolve/resolv.conf
          dest: /etc/resolv.conf
          state: link

      - name: Restart coredns
        shell: echo "restarting coredns"
        notify: "restart coredns"

  - name: UFW
    block:
      - name: Reset
        community.general.ufw:
          state: reset

      # We should ideally use the UFW module here
      - name: Rules
        shell: |
          ufw default allow incoming
          ufw default allow outgoing
          ufw allow in on eth0 to any port 22
          ufw allow in on eth0 to any port 5040
          ufw allow in on eth0 to any port 6040
          ufw allow in on eth0 to any port 27146
          ufw allow in on eth0 to any port 51820
          ufw deny in on eth0

      - name: Enable
        community.general.ufw:
          state: enabled
