---
- name: Storage
  block:
  - name: Copy config
    template:
      src: nvme-hostpath-sc.yml.j2
      dest: /tmp/nvme-hostpath-sc.yml
      owner: root
      group: root
      mode: "0644"

  - name: Apply config
    shell: kubectl apply -f /tmp/nvme-hostpath-sc.yml

  - name: Patch standard storage class
    shell: |
      kubectl patch storageclass microk8s-hostpath -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'

  - name: Patch nvme-hostpath storage class
    shell: |
      kubectl patch storageclass nvme-hostpath -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
