---
- name: Storage
  block:
  - name: mdadm
    block:
    - name: Configure
      command: mdadm --create --verbose {{ raid_md_device }} --level={{ raid_level }} --raid-devices={{ raid_device_count }} {{ raid_devices | replace(',', ' ') }}

    - name: Format
      command: mkfs.btrfs -f {{ raid_md_device }}

    - name: Update initramfs
      command: update-initramfs -u
    
    - name: Get device UUID
      command: "blkid {{ raid_md_device }} | awk '{ print $3 }' | sed -e's/UUID_SUB=//g' -e's/\"//g'"
      register: blkid_uuid

    - name: Update /etc/fstab
      lineinfile:
        path: /etc/fstab
        line: "UUID={{ blkid_uuid.stdout }} {{ mount_point }} btrfs defaults 0 0"
        state: present

    - name: Reload
      command: systemctl daemon-reload

    - name: Create mount point
      ansible.builtin.file:
        path: "{{ mount_point }}"
        state: directory
        mode: "0755"

    - name: Mount
      command: mount -a
    when: raid_setup == "true"

  - name: Copy config
    template:
      src: nvme-hostpath-sc.yml.j2
      dest: /tmp
      owner: root
      group: root
      mode: "0644"

  - name: Apply config
    command: kubectl apply -f /tmp/nvme-hostpath-sc.yml

  - name: Set default
    command: |
      kubectl patch storageclass standard -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'
      kubectl patch storageclass nvme-hostpath -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
